name: Push

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: 'eu-central-1'
  AWS_S3_BUCKET: 'frontend-live-preview'

jobs:
  deploy:
    name: Deploy to frontend.live Preview
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run npm install depending on cache-hit
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build

      - name: Move zip file
        run: zip -r dist.zip ./dist; mv dist.zip dist/
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/integration'

      - name: Extract branch name
        shell: bash
        id: extract_branch_name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Extract repository name
        shell: bash
        id: extract_repository_name
        run: echo "##[set-output name=repository;]$(echo ${GITHUB_REPOSITORY#*/})"

      - name: Deploy to frontend.live
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_SECRET }}
          SOURCE_DIR: 'dist'
          DEST_DIR: '${{ steps.extract_repository_name.outputs.repository }}/${{ steps.extract_branch_name.outputs.branch }}'

      - name: Deploy storybook to frontend.live
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_SECRET }}
          SOURCE_DIR: 'storybook-static'
          DEST_DIR: '${{ steps.extract_repository_name.outputs.repository }}/${{ steps.extract_branch_name.outputs.branch }}/preview'

      - name: Invalidate CDN cache
        uses: awact/cloudfront-action@0.1.2
        env:
          DISTRIBUTION_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DISTRIBUTION_ID }}
          SOURCE_DIR: '${{ steps.extract_repository_name.outputs.repository }}/${{ steps.extract_branch_name.outputs.branch }}'
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_SECRET }}
